include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    camel_case_extensions: true
    cancel_subscriptions: true
    constant_identifier_names: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    flutter_style_todos: true
    implementation_imports: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: false
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    public_member_api_docs: false # Enable if generating public APIs
    require_trailing_commas: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    type_init_formals: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_new: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    valid_regexps: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
